# 파이프라인이 외부에서 동적으로 가중치를 변환시킬 설정 파일을 사전 참조합니다.
include /etc/nginx/conf.d/upstream.inc;
server {
    # 80번 포트로 인입되는 클라이언트 접속을 수신합니다.
    listen 80;
    location / {
        # 'backend' 업스트림 그룹으로 트래픽 프록시 포워딩
        proxy_pass http://backend;
        # 클라이언트의 원본 호스트 정보를 온전히 전달합니다.
        proxy_set_header Host $host;
    }
}
